manifest:
  version: 1.0

  projects:
    - name: zephyr
      url: https://github.com/zephyrproject-rtos/zephyr
      revision: ad056d5454d57002c2b330b301d1e9906dd5fd0f
      import:
        name-allowlist:
          - cmsis_6
          # - hal_nxp
          - hal_stm32
          # - hal_nordic
        path-prefix: deps
